### ISSUE TITLE
Can't connect to any broker using wss

### ISSUE THREAD

**Issue by RobertoD91** [flespi-software/MQTT-Tiles#23]
Testing connection from both https://mqtttiles.flespi.io/ and self hosted version versus this brokers: 
- emqx websocket + TLS
- hivemq.cloud websocket + TLS

nothing work

using https://websocketclient.hivemq.cloud/ i'm able to connect to hivemq broker

in the browser console i get this errror:
```
vendor.c1baebb7.js:76 WebSocket connection to 'wss://***.hivemq.cloud:****/' failed: 
d @ vendor.c1baebb7.js:76
g @ vendor.c1baebb7.js:76
l @ vendor.c1baebb7.js:70
k._setupStream @ vendor.c1baebb7.js:70
k._reconnect @ vendor.c1baebb7.js:70
(anonimo) @ vendor.c1baebb7.js:70
vendor.c1baebb7.js:76 WebSocket connection to 'wss://***.hivemq.cloud:****/' failed: 
d @ vendor.c1baebb7.js:76
```

**Comment by bam80** [comment]
@dexif could you comment?
