### ISSUE TITLE
can't edit connection just by clicking on it

### ISSUE THREAD

**Issue by bam80** [flespi-software/MQTT-Tiles#34]
Click on the middle of the connection row does nothing.
It's somewhat unexpected:
![image](https://github.com/flespi-software/MQTT-Tiles/assets/233979/0e51345c-c97f-46a5-83fa-99e6b3887aaf)

Better use of it would be to enter the Edit mode:
![image](https://github.com/flespi-software/MQTT-Tiles/assets/233979/39390a34-194b-4557-961a-f984f812e953)

**Comment by dexif** [comment]
If you have 2 or more connections, clicking will activate the connection. For active connections, clicking does nothing, yes.

**Comment by bam80** [comment]
To connect/disconnect individual connections, we have an icon on the left already:
![image](https://github.com/flespi-software/MQTT-Tiles/assets/233979/41b88213-96de-434c-8a11-e973e07ddeb4)

So the middle of the row could be used for editing.

**Comment by dexif** [comment]
Implemented ;)
