### ISSUE TITLE
Parse JSON

### ISSUE THREAD

**Issue by CHE77** [flespi-software/MQTT-Tiles#35]
Pls, advise, how to parse JSON {"status":"2"} from subscribe topic
Tried:
status
"status"
["status"]
- no results

**Comment by dexif** [comment]
Please export your widget or board and attach it here.

**Comment by dexif** [comment]
[data.txt](https://github.com/flespi-software/MQTT-Tiles/files/13956430/data.txt)
You can import this board with example.

**Comment by dexif** [comment]
![Screenshot_2024-01-17-00-53-14-79_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/flespi-software/MQTT-Tiles/assets/387234/c8911985-6ca7-4448-be71-171449d80e88)

**Comment by CHE77** [comment]
My topics start with "/"
/user_b32xxxxc/1113900-1488888/alertCounter/status
It could be the problem?
